### PR TITLE
Implement archive datareader

### PR DESCRIPTION
**Pull request by jmcvey3**
Reimplementing the zip and tar archive readers to latest version of tsdat

### CODE REVIEW

**Review by maxwellevin — CHANGES_REQUESTED** [review]
Some changes requested in comments. We should also add tests for these updates

**Review by maxwellevin — APPROVED** [review]
There are some things we should fix later (i.e. using a validator instead of init to set the exclude params, and adding the TarReader), but this looks good for now.

*edit* once the tests are passing, that is

**Review by maxwellevin — CHANGES_REQUESTED** [review]
Tests need to pass

**Comment by jmcvey3** [comment]
> @jmcvey3 what changes did you make to `test/io/data/input.nc`? It looks like at the least the ubuntu-latest, 3.8 test is failing on the line `dataset = reader.read("test/io/data/input.nc")` in the netcdf reader test

@maxwellevin interesting, I didn't. I wonder if this was the issue with the tarreader.

**Comment by maxwellevin** [comment]
@jmcvey3 it looks like the change got committed here: https://github.com/tsdat/tsdat/pull/100/commits/30cb1eea9f804ce4a3cdf7c795dceddfdc86a4bd

Can you revert just that `input.nc` file (you can go back to a previous commit, or just copy it from the main branch)?

**Review by maxwellevin — APPROVED** [review]

**Comment by maxwellevin** [comment]
LGTM. Merging

**Pull request merged**
