### PR TITLE
VAP improvements

### PR DESCRIPTION
**Pull request by jmcvey3**

### CODE REVIEW

**Comment by maxwelllevin** [comment]
@jmcvey3 I can work on the adi.py merge conflicts. I think it's just because I changed the `warnings.warn` to `logger.warning` in an earlier PR and we made some changes to another part of that file here

**Comment by jmcvey3** [comment]
Kk. Still digging into the 2D error. Best I got so far is that it's a tsdat problem.

**Comment by maxwelllevin** [comment]
@jmcvey3 I tried playing around more with the ADI transform thing, and I think I've just about convinced myself that ADI doesn't support time-series transformations where time isn't the first dimension. So `time, range` would work, but `range, time` breaks with a segmentation fault.

**Comment by jmcvey3** [comment]
Yes, I have that much. If I transpose the data in the ingest pipeline, the vap works no problem. If I try to transpose the data after it's read into the vap pipeline, it does the weird transpose bug.

**Pull request merged**
