### PR TITLE
Update QC Functions

### PR DESCRIPTION
**Pull request by jmcvey3**
Update `CheckMonotonic` to be more robust at finding all bad timestamps, and update RemoveFailedValues to be able to drop coordinate values.

### CODE REVIEW

**Review by maxwelllevin — COMMENTED** [review]
This looks pretty good! Could you update or add a test for the updated checker/handler?

**Comment by jmcvey3** [comment]
@maxwelllevin Done! Do you want to pin that version of pydantic to this PR as well?

**Comment by maxwelllevin** [comment]
@jmcvey3 yes, let's pin pydantic to <2.0.0 for now. I'll work on a second PR to update things to work with pydantic >=2 in the coming weeks

**Comment by jmcvey3** [comment]
@maxwelllevin It was pinned, but now we're looking at different errors. I can't replicate the ubuntu one on my machine, and can't tell for mac.

**Comment by maxwelllevin** [comment]
Well, that was partially successful. I think the issues are purely related to environment creation. I forgot that adi_py mac requires python >=3.10, so that's why that one is failing. I'm guessing that for the Ubuntu version a package wasn't installed correctly before, causing the NetCDF writer to crash. That seems to work now.

**Comment by maxwelllevin** [comment]
@jmcvey3 tests are passing now. I used the second workaround described in this issue to resolve it for mac, and it looks like that also helped the linux tests too: https://github.com/conda-incubator/setup-miniconda/issues/274

**Pull request merged**
